name: "CICD for Nginx Webapp using Dockerfile"
on:
    ## Trigger Github Workflow when commit made to main branch
  push:
    branches:
      - "main"
    ## Don't run Github Workflow if changes made to under 'src' folder. 
    paths-ignore:  
      - "src/*"
    ## Trigger Github Workflow when megre request made to main branch
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  nginx-image-build: 
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout repository 
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.USER_GITHUB_TOKEN}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-ubuntu:latest


      

        

        

  

